### PR TITLE
Update node-sass version to 4.12.0

### PR DESCRIPTION
**Pull request by jonnyeom**

### CODE REVIEW

**Comment by jonnyeom** [comment]
I think we should update node-sass to the latest version.
node-sass is failing to build and the plugin is not usable at the moment.

```
error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)’
```
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/path-to-project/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.69-1-MANJARO
gyp ERR! command "/usr/bin/node" "/path-to-project/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /path-to-project/node_modules/nwb-sass/node_modules/node-sass
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by nizarl** [comment]
Hello,

Trying to update to node-js 12.x and not working with nwb-sass 9.0.0.  Error is:

npm ERR! Failed at the node-sass@4.9.2 postinstall script.

How can is use node-sass 4.12 with this project?

Please advise..Thanks
